# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: hotel-reservation
# "service" is the name of this project. This will also be added to your AWS resource names.
service: hotel-reservation

plugins:
  - serverless-plugin-typescript

package:
  individually: true

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: handler.hello
