app: hotel-reservation
service: hotel-reservation

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  stage: local
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:CreateFunction
      Resource: "*"

plugins:
  - serverless-localstack
  - serverless-dotenv-plugin

custom:
  localstack:
    debug: true
    stages:
      - local  # Certifique-se de que o stage 'local' está aqui
    host: http://localhost
    edgePort: 4566
    autostart: true
    lambda:
      mountCode:
    docker:
      sudo: true

functions:
  seedHotel:
    handler: src/presentation/function/seed-hotel.handler
    timeout: 30
    events:
      - http:
          path: /seed-hotel
          method: get

  sign-up:
    handler: src/presentation/function/sign-up.handler
    events:
      - http:
          path: /sign-up
          method: post

  sign-in:
    handler: src/presentation/function/sign-in.handler
    events:
      - http:
          path: /sign-in
          method: post

  deposit:
    handler: src/presentation/function/deposit.handler
    events:
      - http:
          path: /deposit
          method: post
