app: hotel-reservation
service: hotel-reservation

provider:
  name: aws
  runtime: nodejs20.x
  stage: local
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:CreateFunction
      Resource: "*"

plugins:
  - serverless-localstack

custom:
  localstack:
    debug: true
    stages:
      - local  # Certifique-se de que o stage 'local' está aqui
    host: http://localhost
    edgePort: 4566
    autostart: true
    lambda:
      mountCode:
    docker:
      sudo: true

functions:
  hello:
    handler: src/presentation/handler.hello
    events:
      - http:
          path: /hello
          method: get
