app: hotel-reservation
service: hotel-reservation

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  stage: local
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:CreateFunction
      Resource: "*"
    - Effect: Allow
      Action:
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
        - sqs:SendMessage
      Resource:
        - arn:aws:sqs:us-east-1:000000000000:create_reservation.fifo
        - arn:aws:sqs:us-east-1:000000000000:create_reservation_dlq.fifo
        - arn:aws:sqs:us-east-1:000000000000:generate_proof.fifo
        - arn:aws:sqs:us-east-1:000000000000:generate_proof_dlq.fifo

plugins:
  - serverless-localstack
  - serverless-dotenv-plugin

custom:
  localstack:
    debug: true
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    autostart: true
    lambda:
      mountCode:
    docker:
      sudo: true

resources:
  Resources:
    create_reservation_dlq:
      Type: AWS::SQS::Queue
      Properties:
        FifoQueue: true
        QueueName: create_reservation_dlq.fifo

    create_reservation:
      Type: AWS::SQS::Queue
      Properties:
        FifoQueue: true
        QueueName: create_reservation.fifo
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt: [create_reservation_dlq, Arn]
          maxReceiveCount: 5
        VisibilityTimeout: 60

    generate_proof_dlq:
      Type: AWS::SQS::Queue
      Properties:
        FifoQueue: true
        QueueName: generate_proof_dlq.fifo

    generate_proof:
      Type: AWS::SQS::Queue
      Properties:
        FifoQueue: true
        QueueName: generate_proof.fifo
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt: [generate_proof_dlq, Arn]
          maxReceiveCount: 5
        VisibilityTimeout: 60

functions:
  seedHotel:
    handler: src/presentation/function/seed-hotel.handler
    timeout: 30
    events:
      - http:
          path: /seed-hotel
          method: get

  sign-up:
    handler: src/presentation/function/sign-up.handler
    events:
      - http:
          path: /sign-up
          method: post

  sign-in:
    handler: src/presentation/function/sign-in.handler
    events:
      - http:
          path: /sign-in
          method: post

  deposit:
    handler: src/presentation/function/deposit.handler
    events:
      - http:
          path: /deposit
          method: post

  reservation-request:
    handler: src/presentation/function/reservation-request.handler
    events:
      - http:
          path: /reservation-request
          method: post

  reservation:
    handler: src/presentation/function/reservation.handler
    events:
      - sqs: 
          arn: arn:aws:sqs:us-east-1:000000000000:create_reservation.fifo
          batchSize: 1
